# Site settings
title: 40614061 blog
email: 
description: "A Collection of 61#4061 Lab."
baseurl: ""
url: "http://40614061.github.io"
#twitter_username: 
github_username:  40614061

# Build settings
markdown: Typora
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
